# Generated by Django 4.1.6 on 2023-02-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studName', models.CharField(max_length=100)),
                ('studEmail', models.EmailField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='TrainingData',
        ),
    ]
