# Generated by Django 4.1.6 on 2023-02-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_students_delete_trainingdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tecName', models.CharField(max_length=100)),
                ('techEmail', models.CharField(max_length=100)),
                ('techPhone', models.CharField(max_length=12)),
            ],
        ),
    ]
