# Generated by Django 4.1.6 on 2023-03-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_delete_teachers_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Frame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("frame_name", models.CharField(max_length=100)),
                ("frame_type", models.CharField(max_length=50)),
                ("frame_comment", models.TextField()),
                ("frame_image", models.ImageField(upload_to="frame_images/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
